apiVersion: v1
kind: ConfigMap
metadata:
  name: app-vars
data:
  APP_NAME: nginx
  NAMESPACE: default
  IMAGE: nginx
  TAG: 1.25-alpine
  REQ_CPU: 100m
  REQ_MEM: 128Mi
  LIM_CPU: 200m
  LIM_MEM: 256Mi
  PORT: 80
  REPLICAS_DEV: "1"
  REPLICAS_PROD: "3"
  READINESS_PATH: /healthz
  LIVENESS_PATH: /livez
