apiVersion: v1
kind: Service
metadata:
  name: $(APP_NAME)
spec:
  type: LoadBalancer
  selector:
    app: $(APP_NAME)
  ports:
    - name: http
      port: $(PORT)
      targetPort: $(PORT)
      protocol: TCP
