# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
#  # namespace: apps   # ‚Üê add this line
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginx
#   ports:
#   - port: 80
#     targetPort: 80
apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
spec:
  type: LoadBalancer
  selector:
    app: APP_NAME
  ports:
  - port: 80
    targetPort: 80
